---
logging:
  level: INFO
  loggers:
    com.movielibrary: DEBUG
database:
  driverClass: org.postgresql.Driver
  user: arifluthfi
  password: 000123
  url: jdbc:postgresql://localhost:5432/movie_library
  properties:
    charSet: UTF-8
  maxWaitForConnection: 3s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true
  evictionInterval: 10s
  minIdleTime: 1 minute
flyway:
  baselineOnMigrate: true
  validateOnMigrate: true
  locations:
    - filesystem:src/main/java/com/movielibrary/db/migration
  baseLineVersion: 1
server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

